### ISSUE TITLE
I can use a record-schema transformer in my custom exporter

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe-exporter-protobuf#1]
Transforming a record to a protobuf message is something that every exporter using this will need to do, so we might as well provide it out of the box.

Note: it might be a good idea to return pre-filled builder objects as opposed to built messages, makes things more flexible.

AT:

- Provide exporter authors with a minimal API to easily transform `io.zeebe.exporter.Record<?>` to their Protobuf equivalent

**Comment by Zelldon** [comment]
I think first increment is done with your SchemaFactory (copied this class and the other converters in this repository), but feel free to improve on that.
